App\Entity\Product:
  properties:
    name:
      - NotBlank: ~
      - Length:
          min: 3
          max: 100
          minMessage: 'The tittle be at least {{ limit }} characters long'
          maxMessage: 'The tittle cannot be longer than {{ limit }} characters'
          allowEmptyString: false