App\Entity\Product:
  attributes:
    id:
      groups: ['book']
    name:
      groups: ['book']
    cost:
      groups: [ 'book' ]
    image:
      groups: ['book']
    taxonomies:
      groups: ['book']