App\Entity\Product:
  attributes:
    id:
      groups: ['book']
    name:
      groups: ['book']
    description:
      groups: ['book']
    cost:
      groups: ['book']
    cost_final:
      groups: ['book']
    image:
      groups: ['book']
    taxonomies:
      groups: ['book']